use serde::{Deserialize, Serialize};

/// The outer wire envelope for a 1:1 direct message. `sender_user_id`/
/// `sender_curve25519_key` are unauthenticated routing hints, not a
/// security claim: actual authentication is the Olm decryption itself.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DirectEnvelope {
    pub sender_user_id: String,
    pub sender_curve25519_key: String,
    /// Which of the sender's devices encrypted this — same routing-hint
    /// status as `sender_user_id` above. Lets e.g. a fanned-out `CallInvite`
    /// tell which device answered, so the others stop ringing.
    pub sender_device_id: String,
    /// Mirrors `vodozemac::olm::OlmMessage::to_parts()` — 0 for a pre-key
    /// (session-establishing) message, otherwise a normal message.
    pub message_type: u8,
    pub ciphertext: Vec<u8>,
}

/// A file/image attached to a chat message. Carried inside `DirectPayload`
/// and `GroupPayload::Chat` — encrypted (and, for groups, key-rotated) by
/// exactly the same Olm/Megolm sessions as a plain text body, never treated
/// as a second, less-protected channel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttachmentPayload {
    pub filename: String,
    pub mime_type: String,
    /// Whether EXIF metadata was stripped from `data` before it was sent —
    /// surfaced to the recipient so they know whether to trust/inspect it
    /// (see the "view EXIF" UI for the `false` case).
    pub exif_stripped: bool,
    pub data: Vec<u8>,
}

/// The plaintext carried *inside* Olm encryption for a 1:1 exchange. Using
/// the same 1:1 transport for both actual chat messages and group-key
/// distribution keeps the wire format small and reuses the exact same
/// authenticated, forward-secret channel for both.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DirectPayload {
    Chat {
        /// Generated once by whoever composed this message and carried
        /// unchanged through every copy, so a later manual sync can tell
        /// "not seen yet" apart from "already received directly."
        message_id: String,
        body: String,
        #[serde(default)]
        attachment: Option<AttachmentPayload>,
    },
    GroupKeyShare {
        group_id: String,
        session_key_bytes: Vec<u8>,
    },
    /// Sent by someone who's discovered (via the directory server's
    /// `/v1/users/{id}/groups`) that they're apparently a member of a
    /// group but never actually received its key — the one-shot P2P
    /// message that normally delivers it was lost somewhere. Recovery,
    /// not the normal invite path: `GroupKeyShare` above is still what
    /// actually carries the key back in response, this just asks for it.
    /// The recipient must independently verify the sender is really on
    /// the roster before honoring this — see
    /// `AppService::next_event`'s handling of `ChatEvent::GroupKeyRequested`.
    GroupKeyRequest {
        group_id: String,
    },
    /// A 1:1 voice call proposal — "ring" the recipient. `call_id` is
    /// generated by the caller (a UUID) and echoed in every subsequent
    /// message about this same call attempt, since either side might have
    /// more than one call-related message in flight (e.g. a late
    /// `CallEnd` crossing paths with an `CallAccept`) and needs to tell
    /// which call they're about. No group/gossipsub topic exists for a
    /// DM, so unlike a voice *channel* call this can't use presence
    /// broadcast at all — everything about a direct call, including
    /// tearing it down, goes through this same 1:1 Olm-encrypted channel.
    CallInvite {
        call_id: String,
    },
    /// The callee agreed to pick up — sent back over the *caller's*
    /// existing Olm session with them, so the caller learns to start
    /// dialing the actual voice stream.
    CallAccept {
        call_id: String,
    },
    /// The callee explicitly rejected the call (as opposed to `CallEnd`,
    /// used for hanging up an already-connected call or cancelling one
    /// still ringing).
    CallDecline {
        call_id: String,
    },
    /// Ends a call — cancelling one still ringing (either side) or hanging
    /// up one already connected. One variant for both cases: whichever
    /// state the receiver has for `call_id` (a pending invite or an active
    /// call) tells it which situation this is.
    CallEnd {
        call_id: String,
    },
    /// Manual sync between two devices of the *same* account, over this
    /// same 1:1 Olm channel. Single round trip: carries both "what I have
    /// since `since`" and my cursor, so `SyncResponse` needs no second request.
    SyncRequest {
        since: i64,
        messages: Vec<SyncMessage>,
    },
    SyncResponse {
        messages: Vec<SyncMessage>,
    },
}

/// One message as carried by a sync exchange — enough to reconstruct a
/// `storage::StoredMessage` on the receiving end without needing to
/// re-fetch or re-derive anything.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncMessage {
    pub message_id: String,
    pub conversation_id: String,
    pub sender_user_id: String,
    pub body: String,
    pub attachment: Option<AttachmentPayload>,
    pub sent_at: i64,
}

/// The wire envelope for a group message on the group's gossipsub topic.
/// Megolm's signature authenticates the sending session; gossipsub's own
/// signing separately authenticates the publishing network node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GroupEnvelope {
    pub group_id: String,
    pub sender_user_id: String,
    pub session_id: String,
    pub ciphertext: Vec<u8>,
}

/// Plaintext inside a group's Megolm encryption. `channel_id` is a routing
/// field only: every channel reuses the group's one Megolm session and
/// gossipsub topic, since there's no per-channel permissions yet.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum GroupPayload {
    Chat {
        /// Same role as `DirectPayload::Chat::message_id` — see its doc
        /// comment.
        message_id: String,
        channel_id: String,
        body: String,
        #[serde(default)]
        attachment: Option<AttachmentPayload>,
    },
    /// Re-broadcast on a ~5s heartbeat by each participant while a voice
    /// channel call is active. Gossipsub has no history/replay, so this is
    /// how a member who joins a channel after others are already in a call
    /// discovers who else is present — there's no other way to learn that
    /// short of asking. `joined: false` announces a deliberate leave rather
    /// than making everyone else wait for the heartbeat to simply stop.
    VoicePresence { channel_id: String, joined: bool },
    /// Announces that the group's channel list changed (a channel was
    /// created). Carries no data of its own — the directory server is the
    /// source of truth for channel metadata, same as it is for the roster;
    /// this is purely the "something changed, go re-fetch" nudge, mirroring
    /// what `VoicePresence` does for voice-channel membership. A member who
    /// was offline when this went out simply misses it (gossipsub has no
    /// replay), which is what `AppService::refresh_group` being also
    /// callable directly (not just reactively) is for.
    ChannelsChanged,
}
