#!/usr/bin/env bash
#
# Interactive setup for the Seal directory server (crates/directory-server).
# Asks which Linux distribution you're on, installs that distro's build
# prerequisites, builds the release binary, creates a dedicated system user,
# writes a systemd service, and — if you want — fronts it with a domain and
# automatic HTTPS via your choice of Caddy (handles HTTPS itself), or
# nginx/Apache + certbot. Also starts the directory server's built-in
# NAT-traversal relay (Circuit Relay v2 + dcutr) on its own plain-TCP port —
# this is what makes direct-message/group-invite delivery actually work
# between two clients on different networks, not just on a shared LAN; see
# crates/directory-server/src/relay.rs for why it's a background task in the
# same process rather than a separate service. Safe to re-run: it won't
# clobber an existing admin token, relay identity, or overwrite an existing
# web-server site config for a different domain without asking first.
#
# Targets Linux + systemd (so: not Alpine, which uses OpenRC — that would
# need a genuinely different service-file code path, not just a different
# package manager). For local Mac testing, see README.md §3 ("running it in
# dev mode" / the embedded server) or just run:
#   cargo run --release -p directory-server --bin directory-server
#
# Usage: sudo ./scripts/setup-backend.sh

set -euo pipefail

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "This script targets Linux servers with systemd." >&2
  echo "For local/Mac testing, run: cargo run --release -p directory-server --bin directory-server" >&2
  exit 1
fi

if [[ $EUID -ne 0 ]]; then
  echo "This needs root — it creates a system user, writes a systemd unit," >&2
  echo "and installs packages. Re-run with sudo:" >&2
  echo "  sudo $0" >&2
  exit 1
fi

if ! command -v systemctl >/dev/null 2>&1; then
  echo "No systemctl found — this script needs systemd. If you're on Alpine or" >&2
  echo "another OpenRC/non-systemd distro, this script won't work as-is; you'd" >&2
  echo "need an OpenRC init script instead of the systemd unit this writes." >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_USER="seal-directory"
SERVICE_GROUP="seal-directory"
DATA_DIR="/var/lib/seal-directory"
CONFIG_DIR="/etc/seal-directory"
TOKEN_FILE="$CONFIG_DIR/admin-token.env"
UNIT_FILE="/etc/systemd/system/seal-directory.service"
BIN_PATH="/usr/local/bin/directory-server"
RELAY_PORT=4001
# Lives under $DATA_DIR, not $CONFIG_DIR: the systemd unit below only grants
# the service user write access to $DATA_DIR (ProtectSystem=strict makes
# everything else read-only regardless of Unix permissions), and the relay
# identity is generated by the running process itself on first launch, the
# same way directory.sqlite3 is.
RELAY_KEY_FILE="$DATA_DIR/relay-identity.key"

echo "== Seal directory server setup =="
echo "Repo: $REPO_ROOT"
echo

# ---------------------------------------------------------------------------
# 1. Which distro?
# ---------------------------------------------------------------------------
#
# Asked rather than silently auto-detected, per the brief — but pre-filled
# with a best guess from /etc/os-release so it's a one-keystroke confirm on
# the common case rather than real friction.

detect_distro_guess() {
  local id="" id_like=""
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    id="${ID:-}"
    id_like="${ID_LIKE:-}"
  fi
  case "$id $id_like" in
    *debian*|*ubuntu*) echo "debian" ;;
    *fedora*|*rhel*|*centos*) echo "fedora" ;;
    *arch*) echo "arch" ;;
    *suse*) echo "opensuse" ;;
    *) echo "" ;;
  esac
}

prompt_distro() {
  local guess choice
  guess="$(detect_distro_guess)"

  echo "Which Linux distribution family is this?" >&2
  echo "  1) Debian / Ubuntu / Mint / Pop!_OS          (apt)" >&2
  echo "  2) Fedora / RHEL / CentOS Stream / Rocky / Alma (dnf)" >&2
  echo "  3) Arch / Manjaro / EndeavourOS              (pacman)" >&2
  echo "  4) openSUSE / SLES                            (zypper)" >&2
  if [[ -n "$guess" ]]; then
    echo "Detected: looks like '$guess' — press Enter to accept, or pick a number." >&2
  fi

  local default_num=""
  case "$guess" in
    debian) default_num=1 ;;
    fedora) default_num=2 ;;
    arch) default_num=3 ;;
    opensuse) default_num=4 ;;
  esac

  read -rp "Enter 1-4${default_num:+ [$default_num]}: " choice
  choice="${choice:-$default_num}"
  case "$choice" in
    1) echo "debian" ;;
    2) echo "fedora" ;;
    3) echo "arch" ;;
    4) echo "opensuse" ;;
    *) echo "Unrecognized choice: '$choice'." >&2; exit 1 ;;
  esac
}

DISTRO="$(prompt_distro)"
echo "Using: $DISTRO"
echo

# ---------------------------------------------------------------------------
# 2. Per-distro build prerequisites
# ---------------------------------------------------------------------------
# A C compiler + pkg-config (directory-server bundle-compiles SQLite from
# source), plus curl/gnupg/ca-certificates/openssl, which the later Caddy
# and admin-token steps need regardless of which path they take.

install_prereqs_debian() {
  apt-get update
  apt-get install -y build-essential pkg-config curl gnupg ca-certificates openssl
}

install_prereqs_fedora() {
  dnf install -y gcc gcc-c++ make pkgconf-pkg-config curl gnupg2 ca-certificates openssl
}

install_prereqs_arch() {
  pacman -Sy --noconfirm base-devel pkgconf curl gnupg ca-certificates openssl
}

install_prereqs_opensuse() {
  zypper --non-interactive install -y gcc gcc-c++ make pkg-config curl gpg2 ca-certificates openssl
}

echo "-- Installing build prerequisites for $DISTRO --"
"install_prereqs_$DISTRO"
echo

# ---------------------------------------------------------------------------
# 3. Rust toolchain (universal — rustup, not a distro package)
# ---------------------------------------------------------------------------

if ! command -v cargo >/dev/null 2>&1; then
  echo "-- cargo not found --"
  read -rp "Install Rust now via rustup? [Y/n] " install_rust
  install_rust="${install_rust:-y}"
  if [[ "$install_rust" =~ ^[Yy] ]]; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    # shellcheck disable=SC1091
    source "$HOME/.cargo/env"
  else
    echo "Install Rust yourself (https://rustup.rs) and re-run this script." >&2
    exit 1
  fi
fi
echo

# ---------------------------------------------------------------------------
# 4. Build
# ---------------------------------------------------------------------------

echo "-- Building the release binary (this can take a few minutes the first time) --"
# On a shared box, `RUSTC_WRAPPER`/`rustc-wrapper` (env var or
# ~/.cargo/config.toml) may point at a compiler-cache like sccache that's
# configured for *other* projects on this machine but isn't actually
# installed — cargo then fails outright ("could not execute process
# `sccache ...`") instead of just building unwrapped. Try normally first
# (the common case), and only on failure retry with the wrapper cleared for
# this one build — env var and its cargo-config equivalent both, since
# either could be the source — rather than touching global config that may
# be there deliberately for something else on this host.
if ! (cd "$REPO_ROOT" && cargo build --release -p directory-server --bin directory-server); then
  echo "-- Build failed, possibly due to a missing compiler-cache wrapper (e.g. sccache" >&2
  echo "   configured but not installed here) — retrying with RUSTC_WRAPPER cleared for" >&2
  echo "   just this build, not your global cargo config --" >&2
  (cd "$REPO_ROOT" && env -u RUSTC_WRAPPER -u RUSTC_WORKSPACE_WRAPPER \
     CARGO_BUILD_RUSTC_WRAPPER= CARGO_BUILD_RUSTC_WORKSPACE_WRAPPER= \
     cargo build --release -p directory-server --bin directory-server)
fi
install -m 755 "$REPO_ROOT/target/release/directory-server" "$BIN_PATH"
echo "Installed to $BIN_PATH"
echo

# ---------------------------------------------------------------------------
# 5. System user + data/config dirs
# ---------------------------------------------------------------------------

if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  echo "-- Creating system user '$SERVICE_USER' --"
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
else
  echo "-- System user '$SERVICE_USER' already exists, leaving it as-is --"
fi

install -d -o "$SERVICE_USER" -g "$SERVICE_GROUP" -m 750 "$DATA_DIR"
install -d -o root -g root -m 750 "$CONFIG_DIR"
echo

# ---------------------------------------------------------------------------
# 6. Admin token (generated once, never rotated by re-running this script)
# ---------------------------------------------------------------------------

if [[ -f "$TOKEN_FILE" ]]; then
  echo "-- Admin token already exists at $TOKEN_FILE, keeping it --"
else
  echo "-- Generating an admin token --"
  if command -v openssl >/dev/null 2>&1; then
    TOKEN="$(openssl rand -hex 32)"
  else
    TOKEN="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  fi
  printf 'DIRECTORY_ADMIN_TOKEN=%s\n' "$TOKEN" > "$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
  chown root:root "$TOKEN_FILE"
  echo "Saved to $TOKEN_FILE (root-readable only)."
  echo "This is what you pass to 'directory-admin' to purge the server. Back it up somewhere safe:"
  echo "  $TOKEN"
fi
echo

# ---------------------------------------------------------------------------
# 7. Domain + SSL, or not
# ---------------------------------------------------------------------------

# Universal fallback: Caddy's own prebuilt static binary. Used for openSUSE
# (whose repos don't reliably carry Caddy) and as a safety net if a
# distro-specific package install fails for any reason.
#
# NOTE: relies on caddyserver.com's public download endpoint — verify this
# still resolves the way it did when this script was written if it ever
# stops working; Caddy's own install docs (https://caddyserver.com/docs/install)
# are the source of truth.
install_caddy_static_binary() {
  echo "Installing Caddy from its official static binary release..."
  local arch
  case "$(uname -m)" in
    x86_64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    armv7l) arch="armv7" ;;
    *)
      echo "No known Caddy static binary for architecture '$(uname -m)'." >&2
      echo "Install Caddy yourself: https://caddyserver.com/docs/install" >&2
      return 1
      ;;
  esac
  local tmp
  tmp="$(mktemp -d)"
  curl -fsSL "https://caddyserver.com/api/download?os=linux&arch=${arch}" -o "$tmp/caddy"
  chmod +x "$tmp/caddy"
  install -m 755 "$tmp/caddy" /usr/local/bin/caddy
  rm -rf "$tmp"

  mkdir -p /etc/caddy
  touch /etc/caddy/Caddyfile
  if [[ ! -f /etc/systemd/system/caddy.service ]]; then
    cat > /etc/systemd/system/caddy.service <<'EOF'
[Unit]
Description=Caddy
After=network.target

[Service]
Type=notify
ExecStart=/usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile
ExecReload=/usr/local/bin/caddy reload --config /etc/caddy/Caddyfile --force
TimeoutStopSec=5s
LimitNOFILE=1048576
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
  fi
}

install_caddy_debian() {
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    | tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update
  apt-get install -y caddy
}

install_caddy_fedora() {
  dnf install -y 'dnf-command(copr)'
  dnf copr enable -y @caddy/caddy
  dnf install -y caddy
}

install_caddy_arch() {
  pacman -Sy --noconfirm caddy
}

install_caddy_opensuse() {
  # zypper repo availability for Caddy varies by openSUSE version — go
  # straight to the static binary rather than guess a repo name.
  install_caddy_static_binary
}

install_caddy() {
  if command -v caddy >/dev/null 2>&1; then
    echo "Caddy is already installed, skipping."
    return
  fi
  if ! "install_caddy_$DISTRO"; then
    echo "Distro-specific Caddy install failed, falling back to the static binary." >&2
    install_caddy_static_binary
  fi
}

# --- nginx + certbot --------------------------------------------------------
# Unlike Caddy, nginx doesn't get its own HTTPS — it needs a real cert from
# somewhere, which is what certbot's nginx plugin handles: it edits the vhost
# below in place to add the `listen 443 ssl` block and an HTTP->HTTPS
# redirect, and (via the certbot systemd timer/cron job its package installs)
# keeps the cert renewed. `/etc/nginx/conf.d/*.conf` is a drop-in directory
# nginx's default nginx.conf includes on every one of these distros, so one
# file path works everywhere — no need to branch on Debian's separate
# sites-available/sites-enabled convention.

install_nginx_debian() { apt-get install -y nginx; }
install_nginx_fedora() { dnf install -y nginx; }
install_nginx_arch() { pacman -Sy --noconfirm nginx; }
install_nginx_opensuse() { zypper --non-interactive install -y nginx; }

install_nginx() {
  if command -v nginx >/dev/null 2>&1; then
    echo "nginx is already installed, skipping."
  else
    "install_nginx_$DISTRO"
  fi
}

configure_nginx_site() {
  local domain="$1"
  local conf_file="/etc/nginx/conf.d/seal-directory.conf"
  mkdir -p /etc/nginx/conf.d
  if [[ -f "$conf_file" ]]; then
    echo "$conf_file already exists, leaving it as-is."
    return
  fi
  # `\$host` etc. are escaped so nginx (not this shell) expands them —
  # `$domain` is deliberately left unescaped.
  cat > "$conf_file" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $domain;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
  echo "Wrote $conf_file."
}

install_certbot_nginx_debian() { apt-get install -y certbot python3-certbot-nginx; }
install_certbot_nginx_fedora() { dnf install -y certbot python3-certbot-nginx; }
install_certbot_nginx_arch() { pacman -Sy --noconfirm certbot certbot-nginx; }
install_certbot_nginx_opensuse() { zypper --non-interactive install -y python3-certbot python3-certbot-nginx; }

# --- Apache + certbot -------------------------------------------------------
# Apache's drop-in-config conventions genuinely differ per distro (unlike
# nginx's near-universal conf.d), so this branches by $DISTRO for both the
# package/module setup and the vhost path. Arch's default httpd.conf ships
# the proxy/ssl LoadModule lines commented out, so those get uncommented
# in place rather than assuming they're already active.
APACHE_SERVICE="httpd"
case "$DISTRO" in
  debian|opensuse) APACHE_SERVICE="apache2" ;;
esac

install_apache_debian() {
  apt-get install -y apache2
  a2enmod proxy proxy_http ssl >/dev/null
}
install_apache_fedora() {
  # mod_ssl ships as a separate package on Fedora/RHEL; mod_proxy/
  # mod_proxy_http are already active by default via httpd's own
  # conf.modules.d/00-proxy.conf.
  dnf install -y httpd mod_ssl
}
install_apache_arch() {
  pacman -Sy --noconfirm apache
  sed -i \
    -e 's/^#\(LoadModule proxy_module .*\)/\1/' \
    -e 's/^#\(LoadModule proxy_http_module .*\)/\1/' \
    -e 's/^#\(LoadModule ssl_module .*\)/\1/' \
    /etc/httpd/conf/httpd.conf
}
install_apache_opensuse() {
  zypper --non-interactive install -y apache2
  a2enmod proxy proxy_http ssl
}

install_apache() {
  "install_apache_$DISTRO"
}

configure_apache_site() {
  local domain="$1" conf_file=""
  case "$DISTRO" in
    debian) conf_file="/etc/apache2/sites-available/seal-directory.conf" ;;
    fedora) conf_file="/etc/httpd/conf.d/seal-directory.conf" ;;
    arch)
      conf_file="/etc/httpd/conf/extra/seal-directory.conf"
      mkdir -p /etc/httpd/conf/extra
      if ! grep -qF "Include conf/extra/seal-directory.conf" /etc/httpd/conf/httpd.conf; then
        echo "Include conf/extra/seal-directory.conf" >> /etc/httpd/conf/httpd.conf
      fi
      ;;
    opensuse)
      conf_file="/etc/apache2/vhosts.d/seal-directory.conf"
      mkdir -p /etc/apache2/vhosts.d
      ;;
  esac

  if [[ -f "$conf_file" ]]; then
    echo "$conf_file already exists, leaving it as-is."
  else
    cat > "$conf_file" <<EOF
<VirtualHost *:80>
    ServerName $domain
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/
</VirtualHost>
EOF
    echo "Wrote $conf_file."
  fi

  if [[ "$DISTRO" == "debian" ]]; then
    a2ensite seal-directory >/dev/null
  fi
}

install_certbot_apache_debian() { apt-get install -y certbot python3-certbot-apache; }
install_certbot_apache_fedora() { dnf install -y certbot python3-certbot-apache; }
install_certbot_apache_arch() { pacman -Sy --noconfirm certbot certbot-apache; }
install_certbot_apache_opensuse() { zypper --non-interactive install -y python3-certbot python3-certbot-apache; }

# Shared by both nginx and Apache paths: `$1` is certbot's plugin flag
# (`--nginx`/`--apache`), which also tells it which already-written vhost to
# find and edit in place. Re-running against a domain that already has a
# valid cert is a no-op/renewal-check, not a re-issue — certbot itself is
# what makes this safe to re-run, not anything in this script.
run_certbot() {
  local plugin="$1" domain="$2" email="$3"
  local email_args=(--register-unsafely-without-email)
  if [[ -n "$email" ]]; then
    email_args=(-m "$email")
  fi
  certbot "$plugin" -d "$domain" --non-interactive --agree-tos --redirect "${email_args[@]}"
}

echo "Set up a domain with automatic HTTPS?"
echo "  1) Caddy — simplest, handles HTTPS itself, no separate certbot step"
echo "  2) nginx + certbot"
echo "  3) Apache + certbot"
echo "  4) No — front it yourself, or use plain HTTP"
read -rp "Enter 1-4 [1]: " web_choice
web_choice="${web_choice:-1}"

PUBLIC_ADDR="127.0.0.1:8080"
SERVER_URL=""
DOMAIN=""

case "$web_choice" in
  1)
    read -rp "Domain or subdomain to use (e.g. directory.example.com): " DOMAIN
    if [[ -z "$DOMAIN" ]]; then
      echo "No domain entered, aborting." >&2
      exit 1
    fi

    echo
    echo "-- Installing Caddy if it isn't already --"
    install_caddy

    echo
    echo "-- Configuring Caddy for $DOMAIN --"
    CADDY_BLOCK_MARKER="# seal-directory ($DOMAIN)"
    CADDYFILE="/etc/caddy/Caddyfile"
    mkdir -p "$(dirname "$CADDYFILE")"
    touch "$CADDYFILE"
    if grep -qF "$CADDY_BLOCK_MARKER" "$CADDYFILE" 2>/dev/null; then
      echo "Caddyfile already has a block for $DOMAIN, leaving it as-is."
    else
      {
        echo ""
        echo "$CADDY_BLOCK_MARKER"
        echo "$DOMAIN {"
        echo "    reverse_proxy 127.0.0.1:8080"
        echo "}"
      } >> "$CADDYFILE"
      echo "Added a reverse-proxy block to $CADDYFILE."
    fi
    systemctl enable --now caddy >/dev/null 2>&1 || true
    systemctl reload caddy 2>/dev/null || systemctl restart caddy

    echo "Make sure $DOMAIN's DNS A/AAAA record points at this server before" \
         "traffic arrives — Caddy requests the certificate on first request."

    PUBLIC_ADDR="127.0.0.1:8080"
    SERVER_URL="https://$DOMAIN"
    ;;

  2|3)
    read -rp "Domain or subdomain to use (e.g. directory.example.com): " DOMAIN
    if [[ -z "$DOMAIN" ]]; then
      echo "No domain entered, aborting." >&2
      exit 1
    fi
    read -rp "Email for Let's Encrypt renewal notices (recommended, Enter to skip): " CERTBOT_EMAIL

    if [[ "$web_choice" == "2" ]]; then
      echo
      echo "-- Installing nginx if it isn't already --"
      install_nginx
      echo
      echo "-- Configuring nginx for $DOMAIN --"
      configure_nginx_site "$DOMAIN"
      nginx -t
      systemctl enable --now nginx
      systemctl reload nginx
      echo
      echo "-- Installing certbot + its nginx plugin --"
      "install_certbot_nginx_$DISTRO"
      echo
      echo "-- Requesting a certificate from Let's Encrypt --"
      run_certbot --nginx "$DOMAIN" "$CERTBOT_EMAIL"
    else
      echo
      echo "-- Installing Apache if it isn't already --"
      install_apache
      systemctl enable --now "$APACHE_SERVICE"
      echo
      echo "-- Configuring Apache for $DOMAIN --"
      configure_apache_site "$DOMAIN"
      apachectl configtest
      systemctl reload "$APACHE_SERVICE"
      echo
      echo "-- Installing certbot + its Apache plugin --"
      "install_certbot_apache_$DISTRO"
      echo
      echo "-- Requesting a certificate from Let's Encrypt --"
      run_certbot --apache "$DOMAIN" "$CERTBOT_EMAIL"
    fi

    echo "Make sure $DOMAIN's DNS A/AAAA record points at this server before" \
         "traffic arrives — Let's Encrypt validates ownership over HTTP first."

    PUBLIC_ADDR="127.0.0.1:8080"
    SERVER_URL="https://$DOMAIN"
    ;;

  4)
    echo
    echo "Skipping domain/SSL setup — you'll front this yourself, or use it as plain HTTP."
    read -rp "Bind directly to all interfaces on plain HTTP (0.0.0.0:8080)? [y/N] " bind_public
    bind_public="${bind_public:-n}"
    if [[ "$bind_public" =~ ^[Yy] ]]; then
      PUBLIC_ADDR="0.0.0.0:8080"
      SERVER_URL="http://$(hostname -I 2>/dev/null | awk '{print $1}'):8080"
    else
      PUBLIC_ADDR="127.0.0.1:8080"
      SERVER_URL="http://127.0.0.1:8080"
      echo "Bound to loopback only — put your own reverse proxy in front of 127.0.0.1:8080"
      echo "(or SSH-tunnel to it) when you're ready to expose it."
    fi
    ;;

  *)
    echo "Unrecognized choice: '$web_choice'." >&2
    exit 1
    ;;
esac
echo

# ---------------------------------------------------------------------------
# 7b. NAT-traversal relay
# ---------------------------------------------------------------------------
#
# Plain TCP, deliberately not behind Caddy: Caddy only speaks HTTP(S), and
# this is libp2p's own encrypted framing, so it needs its own directly
# dialable port. Reuses whatever public address the previous step already
# established (domain, or a public IP if you chose plain-HTTP-on-all-
# interfaces) — if you chose loopback-only, the relay still runs (useful for
# same-host testing) but stays unadvertised, since advertising an address
# nobody outside this machine can reach wouldn't help anyone.
echo "-- Configuring the NAT-traversal relay --"
RELAY_EXTERNAL_MULTIADDR=""
if [[ -n "${DOMAIN:-}" ]]; then
  RELAY_EXTERNAL_MULTIADDR="/dns4/$DOMAIN/tcp/$RELAY_PORT"
elif [[ "$PUBLIC_ADDR" == 0.0.0.0:* ]]; then
  relay_host="$(hostname -I 2>/dev/null | awk '{print $1}')"
  if [[ -n "$relay_host" ]]; then
    RELAY_EXTERNAL_MULTIADDR="/ip4/$relay_host/tcp/$RELAY_PORT"
  fi
fi

RELAY_EXTERNAL_ENV_LINE=""
if [[ -n "$RELAY_EXTERNAL_MULTIADDR" ]]; then
  RELAY_EXTERNAL_ENV_LINE="Environment=DIRECTORY_RELAY_EXTERNAL_MULTIADDR=$RELAY_EXTERNAL_MULTIADDR"
  echo "Relay will advertise itself at $RELAY_EXTERNAL_MULTIADDR."
  echo "Make sure TCP $RELAY_PORT is reachable from the internet (cloud firewall/security" \
       "group, not just this host's own) — it's a separate port from $PUBLIC_ADDR and Caddy" \
       "doesn't front it."
else
  echo "No public address available (loopback-only setup) — the relay will run but stay" \
       "unadvertised. Contacts on different networks from each other still won't be able to" \
       "reach one another until this server has one; re-run after choosing a domain or a" \
       "public bind if you want that to work."
fi
echo

# ---------------------------------------------------------------------------
# 8. systemd unit
# ---------------------------------------------------------------------------

echo "-- Writing systemd service --"
cat > "$UNIT_FILE" <<EOF
[Unit]
Description=Seal directory server
After=network.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_GROUP
Environment=DIRECTORY_DB_PATH=$DATA_DIR/directory.sqlite3
Environment=DIRECTORY_PUBLIC_ADDR=$PUBLIC_ADDR
Environment=DIRECTORY_ADMIN_ADDR=127.0.0.1:8090
Environment=DIRECTORY_RELAY_ADDR=0.0.0.0:$RELAY_PORT
Environment=DIRECTORY_RELAY_KEY_PATH=$RELAY_KEY_FILE
$RELAY_EXTERNAL_ENV_LINE
# Without this, journalctl -u seal-directory shows only systemd's own
# lifecycle messages, none of the app's own tracing output (relay startup,
# presence writes, request errors) -- it stays quiet with no RUST_LOG set
# at all. info is enough to see startup state and warnings without
# per-request noise (that needs debug).
Environment=RUST_LOG=info
EnvironmentFile=$TOKEN_FILE
ExecStart=$BIN_PATH
Restart=on-failure

ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
NoNewPrivileges=true
ReadWritePaths=$DATA_DIR

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable seal-directory
# Not `enable --now`: `--now` is just `start`, and `start` on an already-
# active unit is a silent no-op — a re-run would rebuild the binary and
# rewrite this unit file (relay port, external multiaddr, whatever else
# changed) but never actually swap the running process for it, since
# systemd doesn't re-exec a live service just because its unit file or the
# binary on disk changed underneath it. `restart` is unconditional either
# way: starts it fresh on a first run, actually restarts it on every
# later one.
systemctl restart seal-directory
echo

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo "== Done =="
echo "Distro:                  $DISTRO"
echo "Server URL for clients:  $SERVER_URL"
echo "Admin token:             $TOKEN_FILE (root-readable only)"
if [[ -n "$RELAY_EXTERNAL_MULTIADDR" ]]; then
  echo "Relay (NAT traversal):   $RELAY_EXTERNAL_MULTIADDR/p2p/<printed in the logs on first start>"
else
  echo "Relay (NAT traversal):   running on 0.0.0.0:$RELAY_PORT but NOT advertised (no public address)"
fi
echo "Logs:                    journalctl -u seal-directory -f"
echo "Purge everything:        cargo run --release -p directory-server --bin directory-admin -- \\"
echo "                           --admin-url http://127.0.0.1:8090 \\"
echo "                           --token \"\$(grep -oP '(?<==).*' $TOKEN_FILE)\" purge"
echo
echo "Point the app at this server by launching it with:"
echo "  P2P_CHAT_DIRECTORY_URL=$SERVER_URL npm run tauri dev"
echo "or by entering it as a custom server in the app's first-run screen / Settings."
